spring:
  datasource:
    url: jdbc:postgresql://ep-restless-dew-aiymc9ap-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_7crnEjBW2ioK

  mail:
    username: kwame@swiftcare.com
    password: password
